### PR TITLE
Add ACEAX Patch to new 34thPRC Misriah Armory Uniforms and Vests

### PR DESCRIPTION
**Pull request by 32Kachoo**
Same as last pull request, all changes up to date, new branch title made to avoid conflict.

### CODE REVIEW

**Review by Lupus590 — CHANGES_REQUESTED** [review]
The marine heavy shoulders are mislabeled as light.
The marine light shoulders are missing entirely.
The ODST uniforms should only have camo variations. For some reason, they have medic and non-medic combinations too.

ODST vests look good.

**Comment by Lupus590** [comment]
Can you also delete the [aceax_gearinfo](https://github.com/34th-Para-Recon-Brimstone-Company/34th-PRC-Aux-Mod/tree/main/src/Addons/aceax_gearinfo) folder? We won't need it since you are adding AAX.

**Comment by 32Kachoo** [comment]
Can you elaborate on the medic thing? There are classes for different medic vests i.e. `34thPRC_ArmourStandard_ODST_M56R_Urban` and `34thPRC_ArmourStandard_ODST_M56R_Urban_Medic`

**Comment by Lupus590** [comment]
> Can you elaborate on the medic thing? There are classes for different medic vests i.e. `34thPRC_ArmourStandard_ODST_M56R_Urban` and `34thPRC_ArmourStandard_ODST_M56R_Urban_Medic`

There are ODST Medic vests, but there are not medic uniforms for the ODST. Yet I have options on the ODST uniform for a medic and non-medic varients but those don't exist and thus break things when I select them.

**Comment by 32Kachoo** [comment]
Alright, give that a shot? Just a couple of basic oversights it seems.

**Comment by Lupus590** [comment]
I forgot about the helmets, those need doing too.

The vests and uniforms look good now though. Well done.

**Comment by Lupus590** [comment]
If you could do the spartan armour as well that would be amazing, but priority should be marines and odst

**Comment by 32Kachoo** [comment]
Helmets added, I'll probably hold off on Spartan gear for now.

**Comment by Lupus590** [comment]
Partly closes #41

**Comment by Lupus590** [comment]
Closing in favour of #179
I made edits but can't push them to your branch.

**Pull request closed without merging**
